### ISSUE TITLE
Please consider to upgrade openssl dependency

### ISSUE THREAD

**Issue by e-oz** [mattnenterprise/rust-imap#24]
openssl can be compiled with single version only, so in single project all crates with dependency of openssl should use same version of the openssl crate. If you'll upgrade dependency (and it may require some small changes in code), this crate will be more easy to add into projects :)

**Comment by vandenoever** [comment]
+1

**Comment by mattnenterprise** [comment]
It was decided to use native-tls instead of openssl because of portability.
