### ISSUE TITLE
sub-process based connections to enable imap over ssh

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mattnenterprise/rust-imap#3]
for local setups and for all ssh setups its nice to use `ssh myuser@myhost' ~/.local/bin/run-imapserver`
as email client

**Comment by mattnenterprise** [comment]
@RonnyPfannschmidt Can you please explain this in more detail?

**Comment by RonnyPfannschmidt** [comment]
instead of using a socket for the input/output, i'd like to run against a process that opens a secure pre-authenticated connection via ssh

so the imap protocol would run against stdin/stdout of a process instead of a socket/ssl socket

**Comment by singron** [comment]
Couldn't you forward a port over ssh and then connect to localhost? e.g.

``` bash
ssh -L 143:localhost:143 remotehost
```

Then connect to localhost:143. This works with all TCP connections without needing library support for ssh.

**Comment by RonnyPfannschmidt** [comment]
nope, port forwarding doesnt always work, running imapd with stdin/out mode does

plus, why is it necessary to run the protocol on top of a socket, ?

**Comment by singron** [comment]
A socket on the loopback interface gets optimized by the kernel into basically a pipe. Ssh has to open a socket to a remote machine regardless. Why doesn't port forwarding work?

**Comment by RonnyPfannschmidt** [comment]
sshd_config disabled in various cases

**Comment by mattnenterprise** [comment]
I have made a change to allow the underlying stream for the client to be customizable. You just need to call : `Client::new(<implements Read and Write>)`. Whatever gets passed into new has to implement the Read and Write traits. @RonnyPfannschmidt Will this help you fix your problem ?

**Comment by RonnyPfannschmidt** [comment]
yes, this allows for just creating a ssh stream with either a ssh protocol abstraction or a subprocess,
well done, lovely :)
