### ISSUE TITLE
Compiling issue - on mac?

### ISSUE THREAD

**Issue by ineiti** [mattnenterprise/rust-imap#34]
Beware: Rust-newbie ahead!

I'm trying to use `rust-imap` on a MacOS X 10.11.6 with rust (cargo-0.17.0-dev) and I copy/pasted the example-program from the `README.md`-file into a new project:

```
cargo new --bin testimap
cd testimap
cat <<EOF > src/main.rs
extern crate imap;
extern crate openssl;
...
		Err(e) => println!("Error Fetching email 2: {.unwrap();
}
EOF
echo imap = \"0.2.1\" >> Cargo.toml 
cargo build
```

This outputs the following for me:

```
Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.21
   Compiling openssl v0.8.3
   Compiling void v1.0.2
   Compiling regex-syntax v0.4.0
   Compiling utf8-ranges v1.0.0
   Compiling openssl-sys v0.7.17
   Compiling thread-id v3.0.0
   Compiling bitflags v0.7.0
   Compiling lazy_static v0.2.6
   Compiling memchr v1.0.1
   Compiling unreachable v0.1.1
   Compiling thread_local v0.3.3
   Compiling aho-corasick v0.6.3
   Compiling regex v0.2.1
   Compiling imap v0.2.1
   Compiling testimap v0.1.0 (file:///Users/ineiti/IdeaProjects/testimap)
error[E0463]: can't find crate for `openssl`
 --> src/main.rs:2:1
  |
2 | extern crate openssl;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `testimap`.
```

Is there a problem with the MacOSX-openssl support? I installed it with `brew install openssl`, but I never know which package it takes. Is this a rust-imap issue? openssl-issue?

**Comment by jonhoo** [comment]
Hey @ineiti!

Sorry for the super late response. When working with Rust code, you also need to declare your dependencies. Your project is using `openssl` to connect (see the `extern crate openssl`) line, and that means you must also declare `openssl` as a dependency in your `Cargo.toml` file. See for example https://github.com/jonhoo/buzz/blob/925cdaa8160fcbbba3d25823764ec5d6a7aff3db/Cargo.toml#L23. Once you've done that, things should work as expected.
