### ISSUE TITLE
Port to native-tls

### ISSUE THREAD

**Issue by jrmuizel** [mattnenterprise/rust-imap#35]
The native-tls crate has a better portability story than just using openssl does.

**Comment by mattnenterprise** [comment]
@jonhoo What do you think of using native-tls over openssl ? The appveyor build is really complicated because of using openssl. I also see complaints from others about openssl being required to use the same version for it in an entire project.

**Comment by jonhoo** [comment]
Seems like a good idea to me! It also looks like the transition should be relatively straightforward. @jrmuizel is this something you might want to try out (I'd be happy to give guidance)?

**Comment by jonhoo** [comment]
nvm, I had some spare time, so implemented it in #43. watch that+this space.
