### ISSUE TITLE
Detect closed connections

### ISSUE THREAD

**Issue by jonhoo** [mattnenterprise/rust-imap#38]
The current code (in [`Client::readline`](https://github.com/mattnenterprise/rust-imap/blob/master/src/client.rs#L485)) ignores the case when `self.stream.read` returns `Ok(0)`, and simply keeps on spinning. However, when `Ok(0)` is returned, this is a signal that the underlying stream has been closed by the other end (see in particular the openssl error code https://docs.rs/openssl/0.9.17/openssl/ssl/enum.Error.html#variant.ZeroReturn which is translated into `Ok(0)` when using the `Read` trait, the documentation on [`Read::read`](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#tymethod.read), and the manpage for the `recv` system call).

The right thing for rust-imap to do is probably to translate this into an error, or alternatively to try and re-establish the connection. It is not entirely clear, but I would guess the former is most appropriate. The infinite spinning it does now certainly isn't :)

**Comment by jonhoo** [comment]
Probably worth noting that this is effectively a duplicate of #23; fe398fb53112c004541885caa51d7e79fdb85ee7 is not a complete fix.

**Comment by jonhoo** [comment]
Out of curiosity, is there a reason why the [`read_line`](https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_line) function from the standard library isn't used here? It's more efficient (since it doesn't read one byte at a time), and should correctly handle EOF automatically.

**Comment by mattnenterprise** [comment]
The only reason that was never used is because the library never used a stream that fulfilled the BufRead trait.

**Comment by mattnenterprise** [comment]
I would be happy to take a pull request using that read_line function instead.
