### ISSUE TITLE
Switch from kcov to cargo-tarpaulin

### ISSUE THREAD

**Issue by jonhoo** [mattnenterprise/rust-imap#45]
@mattnenterprise in [`addr2line`](https://github.com/gimli-rs/addr2line), we're [switching](https://github.com/gimli-rs/addr2line/pull/54) to `cargo-tarpaulin` for code coverage, and completely removing `cargo-travis`. Might be something we'll want to do here as well.

**Comment by mattnenterprise** [comment]
Do you mean you are removing `travis-cargo` (I know the names are really similar) ? I replaced `travis-cargo` with `cargo-travis` in #44. So we just use `cargo-travis` for code coverage. Would there be any advantages to using `cargo-tarpaulin` over `cargo-travis` for code coverage ?

**Comment by jonhoo** [comment]
Well, `cargo-travis` is only needed because it provides a hook for `kcov`. `cargo-tarpaulin` doesn't use `kcov`; it's written in pure rust, and designed specifically to integrate well with Cargo.

**Comment by mattnenterprise** [comment]
Sounds like a reason to give it a try. @jonhoo Do you want to work on a pull request for using `cargo-tarpaulin` ?
