### ISSUE TITLE
APPEND support is incomplete

### ISSUE THREAD

**Issue by cyphar** [mattnenterprise/rust-imap#60]
At the moment `APPEND` only supports setting the body of the message. However, RFC3501 allows users to specify the flag set to be applied to a message, as well as the date the message was received. Quoting the specification:

```
6.3.11. APPEND Command

   Arguments:  mailbox name
               OPTIONAL flag parenthesized list
               OPTIONAL date/time string
               message literal
```

We could change the `append` method to:

```rust
use chrono::DateTime;
use chrono::offset::Utc;

fn append(&mut self, folder: &str,
          flags: Vec<String>,
          datetime: DateTime<Utc>,
          message: &[u8]) { /* ... */ } 
```

**Comment by jonhoo** [comment]
Let's move further discussion to https://github.com/jonhoo/rust-imap/issues/60.
