### ISSUE TITLE
Allow jonhoo publish access to the crate

### ISSUE THREAD

**Issue by mattnenterprise** [mattnenterprise/rust-imap#69]
@jonhoo Would it be easier just to move this repo to an organization so you can publish to crates.io ?
The process of adding others is described at https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

I guess we could create a dummy organization and team, but never move the repo as an alternative. If you didn't want to move the repo.

**Comment by jonhoo** [comment]
Adding me as an owner should be sufficient to allow me to publish new versions, and should require an org. In particular, you should just be able to do:

```console
$ cargo owner --add jonhoo
```

But moving this repo into an org is probably a good idea anyway. In part because we could then possibly combine some of the work with what @djc and @sanmai-NL have been doing on `imap-proto` and `tokio-imap`. Gathering all the imap stuff in one place would be nice :)

**Comment by mattnenterprise** [comment]
Got a particular org name in mind ? Is 'rust-imap' good enough ?

**Comment by jonhoo** [comment]
Yeah, I think `rust-imap` is as good an org name as any! The question is more so what to name this repository after we move it. If we're also thinking we might move `imap-proto` and `tokio-imap` in there, just `imap` may be somewhat ambiguous. Although maybe it's fine. Thoughts @djc / @sanmai-NL ?

**Comment by djc** [comment]
I was also thinking `rust-imap` would be a good org name, and we can consider moving `tokio-imap` (which these includes the `imap-proto` repo) into that org, as well.

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by sanmai-NL** [comment]
@jonhoo: are you co-maintainer now? I cannot see it in the GitHub UI it appears.

**Comment by jonhoo** [comment]
@sanmai-NL nope. I have push access to the repo, but am not an "Owner" on crates.io, so cannot publish new versions.

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by jonhoo** [comment]
ping @mattnenterprise

**Comment by mtorromeo** [comment]
I hope this can be resolved soon. I was already forced to use the git version due to the lack of updates and the issues with `native-tls` and the latest openssl but now I am just using my own fork.

**Comment by jonhoo** [comment]
To those watching this issue: I've pinged the crates.io team and they're looking into what we might be able to do to move forward :)

**Comment by djc** [comment]
@jonhoo any update from the team? @mattnenterprise pretty please?

**Comment by jonhoo** [comment]
> It will be a few weeks before we can take any action
>  - @sgrif on Oct 13

**Comment by jonhoo** [comment]
Brief update from today:
> @sgrif: We have to give the current owner several weeks to respond, sorry
> @sgrif: I will let you know when enough time has passed
> @jonhoo: Okay, I understand :) How much time is generally afforded for owners to respond?
> @sgrif: It's a case by case thing. Typically a few weeks though.
> @sgrif: I can assure you it's not something that's going to get forgotten about. It's just a matter of letting enough time pass

**Comment by pycebs** [comment]
@mattnenterprise Can you please take care of this? According to your GitHub history it looks like you're still active. This will only take a few seconds and would help a lot of people.

**Comment by dario23** [comment]
@pycebs as i understand it, @jonhoo is already in talks with the crates.io people, but it takes some time (according to the crates.io policies and being fair to the current/previous owner on crates.io), so there's nothing that can be done in just a few minutes currently :-(

**Comment by jonhoo** [comment]
@pycebs sadly it seems like @mattnenterprise is no longer watching this repository or checking the GitHub interface -- they're only pushing to private repositories. I've tried to reach out by e-mail, but to no avail. @dario23 is right that I'm touch with the crates.io people, and that transitioning through that process takes a while (we don't want people to be able to easily grab other people's crates after all!). I pinged @sgrif again yesterday, but haven't heard back yet.

**Comment by MarkusBarthlen** [comment]
Would it make sense to rename/fork the project (maybe even temporarily)?

Edit: Nevermind, I did not know how easy it was to depend on the latest github state of a library.

**Comment by jonhoo** [comment]
Still no follow-up from the crates.io team sadly. I don't want to keep pinging them given that @sgrif said they'd get back to me, though #94 is pretty troubling. Is anyone bottlenecked by having to depend on `git` for the time being? Trying to determine how critical bumping `imap` on crates.io is :)

**Comment by sanmai-NL** [comment]
@jonhoo: We’re not. Thanks for all your effort...

**Comment by pycebs** [comment]
I added the github url to my cargo.toml and it works just fine.  So it's not super urgent.

`imap = { git = "https://github.com/mattnenterprise/rust-imap.git" }`

**Comment by jonhoo** [comment]
@sgrif told me yesterday that he's hoping to get a resolution to this very soon!

**Comment by jonhoo** [comment]
I now have publish access! I made some serious revisions to docs and crate organization earlier today in f83742dc3d37fb005055bfb5531d63569fd0ee27, and will push out `imap 0.9.0` tomorrow! :tada:

**Comment by pycebs** [comment]
First of all: Congratulations to finally getting publish access. This actually happened faster than I thought.

But also: What an update! 0.9 docs improvements and look fantastic!!

**Comment by jonhoo** [comment]
`imap 0.9` is now finally out :tada:
And look at [those docs](https://docs.rs/imap/0.9)!
