### ISSUE TITLE
Using extern crate, compile issue.

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [mattnenterprise/rust-imap#83]
I tried to compile my freshly created Hello World Rust application with the ``imap`` crate.
After doing so, the compiler stumbles upon a compile error for the ``unrachable`` library, saying it cannot find the ``void`` crate it wants to use.

See also my StackOverflow question, [here](https://stackoverflow.com/questions/51692485/rust-cant-find-extern-crate-for-a-extern-crate).
I have more info to be found there in terms of code snippets and things I've tried.

**Comment by jonhoo** [comment]
I'll need more information to reproduce this. The code you give in your SO post works fine for me:
```toml
[package]
name = "imap_project"
version = "0.1.0"
authors = ["Name & Email"]

[dependencies]
imap = "0.8.1"
```
```rust
extern crate imap;
fn main() {
    println!("Hello, world!");
}
```
```console
$ cargo check
    Checking bufstream v0.1.3
    Checking memchr v1.0.2
    Checking nom v3.2.1
    Checking imap-proto v0.4.1
    Checking imap v0.8.1
    Checking imap_project v0.1.0 (file:///home/jon/dev/tmp/imap_project)
    Finished dev [unoptimized + debuginfo] target(s) in 5.79s
$ cargo run
   Compiling bufstream v0.1.3
   Compiling memchr v1.0.2
   Compiling nom v3.2.1
   Compiling imap-proto v0.4.1
   Compiling imap v0.8.1
   Compiling imap_project v0.1.0 (file:///home/jon/dev/tmp/imap_project)
    Finished dev [unoptimized + debuginfo] target(s) in 8.51s
     Running `/home/jon/dev/tmp/cargo-target/debug/imap_project`
Hello, world!
```

**Comment by jonhoo** [comment]
I'll close this given that I didn't hear anything more.
