### ISSUE TITLE
What is the situation with pushing updates to crates.io ?

### ISSUE THREAD

**Issue by pycebs** [mattnenterprise/rust-imap#90]
Hello everyone.

So the last push to crates.io was in April. However there were quite a few updates since then on github. Also I've seen a few issues being opened about this as well.

So what is the current situation here? Is the original contributor not responding? Can he/she not just add other contributors to the "Allowed to publish to crates.io" list? Is the original contributor sick? I really like this crate, but it'd be much more helpful if there'd be up to date versions on crates.io

Could someone enlighten me please?

**Comment by jonhoo** [comment]
The original author, @mattnenterprise, has not been available since ~April. The plan was to give me publish access to the crate, and maybe even move it to a GitHub organization (see #69), but there's been no update on that since @mattnenterprise went silent. I've tried e-mailing him too, but haven't gotten any reply.

**Comment by jonhoo** [comment]
Until the situation resolves, you should either use this as a `git` dependency, or use [`tokio-imap`](https://github.com/djc/tokio-imap) instead which is under the custody of @djc.

Long term, if nothing changes, my guess is that we'll either publish this under a different name, or that we'll build a synchronous compatibility layer on top of `tokio-imap` to avoid duplication of effort.

**Comment by pycebs** [comment]
Wow your response time is very fast!

Thanks for letting me know. I'm aware of tokio-imap but I cannot assess if it has all the features that I need. Do you have any insights into this?

What I need to be able to do is this:
- Get all messages from a selected IMAP folder
- Get all FLAGS for every message as well
- Ability to add and remove FLAGS for any one selected email (mark as read/unread, flagged/unflagged, etc)
- Ability to delete/move/copy a single message to a folder
- IDLE would be lovely, but it's not really necessary.

How much of this can be done by rust-imap? And how much of this can be done by tokio-imap?

**Comment by jonhoo** [comment]
`tokio-imap` _can_ do all of that, but it (currently) provides very low-level bindings; you basically have to issue all the IMAP requests yourself (see [the docs](https://docs.rs/tokio-imap/0.3.0/tokio_imap/client/struct.Client.html)). I think @djc's plan is for that situation to improve, but don't know their timeline.

As for this crate, I've pinged the crates.io maintainers, and we may be able to move forward with publishing the crate some time soon. Stay tuned! This crate (`rust-imap`) should be able to provide all those features I think. You can take a look at [`Client`](https://docs.rs/imap/0.8.1/imap/client/struct.Client.html) for the kind of functionality that's available. We even support IDLE!

**Comment by pycebs** [comment]
Wow awesome. Definitely sticking with rust-imap then. Thanks for your help!

**Comment by jonhoo** [comment]
You can start trying it out with:
```toml
[dependencies]
imap = { git = "https://github.com/mattnenterprise/rust-imap.git" }
```

**Comment by djc** [comment]
Just to make it clear, tokio-imap is currently more like passively maintained: I don't have any active projects that are using it, so I'll just try to fix issues as they get filed and review PRs.
