### ISSUE TITLE
Compilation error - use nom

### ISSUE THREAD

**Issue by whl36512** [mattnenterprise/rust-imap#93]
Hi, thank you for create this package. Very useful.
One small thing.  When compiling, I got
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> /root/.cargo/git/checkouts/rust-imap-eddc04189818a7a1/f02950a/src/client.rs:776:25
    |
776 |                     Err(nom::Err::Incomplete(..)) => {
    |                 

I added 
use nom;
to src/client.rs, and everything was fine.

Can you please fix it?

**Comment by jonhoo** [comment]
Thanks! Very weird that this didn't fail for me. It somehow compiles both on `stable`, `beta`, and `nightly` on [Travis](https://travis-ci.org/mattnenterprise/rust-imap/builds/449547978), and compiles locally for me :/

**Comment by whl36512** [comment]
i am using
rustc 1.29.0 (aa3ca1994 2018-09-11)

don't know if it makes any difference.

Thx for fixing it so quickly
