### ISSUE TITLE
Client.authenticate() should Base64 encode the data from the Authenticator

### ISSUE THREAD

**Issue by kmkaplan** [mattnenterprise/rust-imap#95]
[RFC 3501 6.2.2. AUTHENTICATE Command](https://tools.ietf.org/html/rfc3501#section-6.2.2) says that
> The client response consists of a single line consisting of a BASE64 encoded string.

So the Base64 encoding is really part of the IMAP protocol. The [PLAIN SASL mecanism specification](https://tools.ietf.org/html/rfc2595#section-6)  even does _not_ show the encoding. That means that every `Authenticator::process` method has to do the Base64 encoding. It would be easier for everybody if that process was done inside `Client.do_auth_handshake()` for every `Authenticator`.

If that sounds reasonnable I can provide a pull request.

**Comment by jonhoo** [comment]
I agree, that seems reasonable! I'd be happy to review a PR.

**Comment by kmkaplan** [comment]
OK, I'll do that.
